elasticsearch:
  address: ["http://blog-elasticsearch-z6g.public.cn-beijing.es-serverless.aliyuncs.com:9200"]
  username: "blog-elasticsearch-z6g"
  password: "Jiang19780809@"
  index: "article"

mysql:
  host: "rm-bp159w6ur7y66s35dro.mysql.rds.aliyuncs.com"
  port: 3306
  username: "blog"
  password: "Jiang19780809@"
  database: "blog" 
  table: "articles" 
