version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nginx.key:/etc/ssl/certs/nginx.key
      - ./nginx/ssl/nginx.crt:/etc/ssl/certs/nginx.crt
      - ./frontend/dist/:/usr/share/nginx/html/
    ports:
      - 443:443
  backend:
    build:
      context: ./backend
      dockerfile: ./.dockerfile
    container_name: blog_backend
    restart: always
    expose: 
      - "8080"

     